image: ubuntu:24.04

stages:
  - test
  - docs_deploy

.setup_linux: &setup_linux |
  DEBIAN_FRONTEND=noninteractive

  # set time-zone
  TZ=Canada/Pacific
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

  # for downloading
  apt-get update -qq
  apt-get install -y --no-install-recommends curl gnupg ca-certificates

.setup_cpp: &setup_cpp |
  curl -o ./setup-cpp -LJ "https://github.com/aminya/setup-cpp/releases/download/v0.41.1/setup-cpp-x64-linux"
  chmod +x ./setup-cpp
  ./setup-cpp --compiler $compiler --cmake true --ninja true --ccache true --vcpkg true --task true --gcovr 7 --doxygen true
  source ~/.cpprc

.test: &test |
  task coverage
  task coverage_release
  task install

test_linux_llvm:
  stage: test
  variables:
    compiler: llvm
  script:
    - *setup_linux
    - *setup_cpp
    - *test
    - |
      # Build the docs
      task docs

      # On the main branch
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        # Prepare the docs
        cp -r ./build/html/ ./public
      fi
  artifacts:
    expire_in: 4 weeks
    paths:
      - package
      - public

test_linux_gcc:
  stage: test
  variables:
    compiler: gcc
  script:
    - *setup_linux
    - *setup_cpp
    - *test

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image: alpine:latest
  stage: docs_deploy
  script: "echo 'Deploying website to https://$CI_PAGES_URL/'"
  artifacts:
    paths:
      - public
