stages:
  - build

.standard-rules:       # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - "build/*/*.tar.gz"

.setup_linux: &setup_linux |
  echo -e "\e[0Ksection_start:`date +%s`:my_setup_linux[collapsed=true]\r\e[0KHeader of the setup linux collapsible section"
  DEBIAN_FRONTEND=noninteractive

  # XXX WHY? set time-zone
  # TZ=Canada/Pacific
  # ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

  # for downloading
  apt-get update -qq
  apt-get install -y --no-install-recommends curl gnupg ca-certificates python3-pip
  echo -e "\e[0Ksection_end:`date +%s`:my_setup_linux\r\e[0K"

.setup_cpp: &setup_cpp |
  echo -e "\e[0Ksection_start:`date +%s`:my_setup_cpp[collapsed=true]\r\e[0KHeader of the setup cpp collapsible section"
  curl -LJO "https://github.com/aminya/setup-cpp/releases/download/v0.33.0/setup-cpp-x64-linux"
  chmod +x setup-cpp-x64-linux
  ./setup-cpp-x64-linux --compiler $compiler --ccache true --vcpkg true --clangtidy true
  source ~/.cpprc
  pwd && mkdir -p build/coverage
  echo -e "\e[0Ksection_end:`date +%s`:my_setup_cpp\r\e[0K"
  clang-tidy --version
  python3 --version
  python3 -m pip install cmake ninja gcovr
  cmake --version
  ninja --version

# XXX not longer used! CK
.task: &test |
  task coverage
  task coverage_release
  task install

.build:
  script:
    - *setup_cpp
    - echo -e "\e[0Ksection_start:`date +%s`:my_build[collapsed=true]\r\e[0KHeader of the build collapsible section"
    - cmake --workflow --preset ${CI_compiler}-debug
    - gcovr .
    - cmake --workflow --preset ${CI_compiler}-release
    - echo -e "\e[0Ksection_end:`date +%s`:my_build\r\e[0K"

default:               # Add a default section to define the `image` keyword's default value
  image: ubuntu:22.04
  before_script:
    - *setup_linux

test_linux_llvm:
  stage: build
  variables:
    compiler: llvm
    CI_compiler: clang
  extends:
    - .standard-rules  # Reuse the configuration in `.standard-rules` here
    - .build

test_linux_gcc:
  stage: build
  variables:
    compiler: gcc
    CI_compiler: gcc
  extends:
    - .standard-rules  # Reuse the configuration in `.standard-rules` here
    - .build

# see https://docs.gitlab.com/ee/ci/jobs/#custom-collapsible-sections
# job1:
#   script:
#     - echo -e "\e[0Ksection_start:`date +%s`:my_first_section[collapsed=true]\r\e[0KHeader of the 1st collapsible section"
#     - echo 'this line should be hidden automatically after loading the job log'
#     - echo -e "\e[0Ksection_end:`date +%s`:my_first_section\r\e[0K"
